blank_issues_enabled: false
contact_links:
- name: Questions, feature requests, and more 💬
  url: https://github.com/bytemare/hpke/discussions
  about: Do you need help? Did you make something with hpke? Do you have an idea? Tell us about it!